language: php

php:
    - 5.6
    - 7.0
    - 7.1

install:
    - composer install -n

script:
    - ./bin/phpunit --coverage-clover=coverage.clover
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
